### PR TITLE
Redirect Pages to apptainer.org

### PR DESCRIPTION
**Pull request by CannonLock**
This PR swaps all the previous html out for html pages with meta redirects. 

Without server options this is the next [best thing](https://developers.google.com/search/docs/advanced/crawling/301-redirects), but unfortunately there is a little flash before getting sent to the new page. 

I tested this by setting up the website on my own github -> https://cannonlock.github.io/singularity-web//index.html and then requesting all the files -> reading their meta redirect -> checking that that page gave status 200 as well.

### CODE REVIEW

**Comment by DrDaveD** [comment]
- Fixes #14

**Comment by DrDaveD** [comment]
@CannonLock Please change all the "please wait well we redirect" to "please wait while we redirect".

**Comment by CannonLock** [comment]
@brianclemens You will also have to change the branch that is serving the website to gh-pages for this to take effect.

**Comment by DrDaveD** [comment]
It's looking good now, thanks Brian & Cannon.

**Pull request merged**
